[project]
authors = [
  {name = "Mattia Bondanza", email = "mattia.bondanza@unipi.it"},
  {name = "Filippo Lipparini", email = "filippo.lipparini@unipi.it"},
  {name = "Benedetta Mennucci", email = "benedetta.mennucci@unipi.it"},
]
classifiers = [
  "Programming Language :: Python :: 3",
]
dependencies = [
  "numpy >= 1.17",
]
description = "Python interface of OpenMMPol library"
dynamic = ["version"]
license = {text = "LGPL v3"}
name = "pyopenmmpol"
requires-python = ">=3.7"

[project.urls]
"Bug Tracker" = "https://github.com/Molecolab-Pisa/OpenMMPol/issues"
"Homepage" = "https://github.com/Molecolab-Pisa/OpenMMPol"

[build-system]
build-backend = "setuptools.build_meta"
requires = [
  "setuptools>=60",
  "setuptools-scm>=8.0",
]

[tool.setuptools.package-dir]
pyopenmmpol = "./pyopenmmpol"

[tool.setuptools.package-data]
pyopenmmpol = ["*.so"]
