#ifndef __F_CART_COMPONENTS__
#define __F_CART_COMPONENTS__

#define _amoeba_D_ 1
!! Index of direct (D) field and dipoles in AMOEBA FF (true dipoles)
#define _amoeba_P_ 2
!! Index of polarization (P) field and dipoles in AMOEBA FF (Lagrange multiplier)

#define _self_ 1
#define _iz_   2
#define _ix_   3
#define _iy_   4
!! Slots of the 4 atoms defining a multipole's molecular frame (self,iz,ix,iy)
!! as packed in rotation_matrix's dr/d2r and rotate_multipoles's ddip/dqua/
!! d2dip/d2qua. iy is kept last as not every convention uses it.

#define _x_ 1
#define _y_ 2
#define _z_ 3

#define _xx_ 1
#define _xy_ 2
#define _yy_ 3
#define _xz_ 4
#define _yz_ 5
#define _zz_ 6
#define _yx_ _xy_
#define _zx_ _xz_
#define _zy_ _yz_

#define _xxx_ 1
#define _xxy_ 2
#define _xxz_ 3
#define _xyy_ 4
#define _xyz_ 5
#define _xzz_ 6
#define _yyy_ 7
#define _yyz_ 8
#define _yzz_ 9
#define _zzz_ 10
#define _xyx_ _xxy_
#define _xzx_ _xxz_
#define _xzy_ _xyz_
#define _yxx_ _xxy_
#define _yxy_ _xyy_
#define _yxz_ _xyz_
#define _yyx_ _xyy_
#define _yzx_ _xyz_
#define _yzy_ _yyz_
#define _zxx_ _xxz_
#define _zxy_ _xyz_
#define _zxz_ _xzz_
#define _zyx_ _xyz_
#define _zyy_ _yyz_
#define _zyz_ _yzz_
#define _zzx_ _xzz_
#define _zzy_ _yzz_

/* xxxx */
#define _xxxx_ 1
/* xxxy */
#define _xxxy_ 2
#define _xxyx_ _xxxy_
#define _xyxx_ _xxxy_
#define _yxxx_ _xxxy_
/* xxxz */
#define _xxxz_ 3
#define _xxzx_ _xxxz_
#define _xzxx_ _xxxz_
#define _zxxx_ _xxxz_
/* xxyy */
#define _xxyy_ 4
#define _xyxy_ _xxyy_
#define _xyyx_ _xxyy_
#define _yxxy_ _xxyy_
#define _yxyx_ _xxyy_
#define _yyxx_ _xxyy_
/* xxyz */
#define _xxyz_ 5
#define _xxzy_ _xxyz_
#define _xyxz_ _xxyz_
#define _xyzx_ _xxyz_
#define _xzxy_ _xxyz_
#define _xzyx_ _xxyz_
#define _yxxz_ _xxyz_
#define _yxzx_ _xxyz_
#define _yzxx_ _xxyz_
#define _zxxy_ _xxyz_
#define _zxyx_ _xxyz_
#define _zyxx_ _xxyz_
/* xxzz */
#define _xxzz_ 6
#define _xzxz_ _xxzz_
#define _xzzx_ _xxzz_
#define _zxxz_ _xxzz_
#define _zxzx_ _xxzz_
#define _zzxx_ _xxzz_
/* xyyy */
#define _xyyy_ 7
#define _yxyy_ _xyyy_
#define _yyxy_ _xyyy_
#define _yyyx_ _xyyy_
/* xyyz */
#define _xyyz_ 8
#define _xyzy_ _xyyz_
#define _xzyy_ _xyyz_
#define _yxyz_ _xyyz_
#define _yxzy_ _xyyz_
#define _yyxz_ _xyyz_
#define _yyzx_ _xyyz_
#define _yzxy_ _xyyz_
#define _yzyx_ _xyyz_
#define _zxyy_ _xyyz_
#define _zyxy_ _xyyz_
#define _zyyx_ _xyyz_
/* xyzz */
#define _xyzz_ 9
#define _xzyz_ _xyzz_
#define _xzzy_ _xyzz_
#define _yxzz_ _xyzz_
#define _yzxz_ _xyzz_
#define _yzzx_ _xyzz_
#define _zxyz_ _xyzz_
#define _zxzy_ _xyzz_
#define _zyxz_ _xyzz_
#define _zyzx_ _xyzz_
#define _zzxy_ _xyzz_
#define _zzyx_ _xyzz_
/* xzzz */
#define _xzzz_ 10
#define _zxzz_ _xzzz_
#define _zzxz_ _xzzz_
#define _zzzx_ _xzzz_
/* yyyy */
#define _yyyy_ 11
/* yyyz */
#define _yyyz_ 12
#define _yyzy_ _yyyz_
#define _yzyy_ _yyyz_
#define _zyyy_ _yyyz_
/* yyzz */
#define _yyzz_ 13
#define _yzyz_ _yyzz_
#define _yzzy_ _yyzz_
#define _zyyz_ _yyzz_
#define _zyzy_ _yyzz_
#define _zzyy_ _yyzz_
/* yzzz */
#define _yzzz_ 14
#define _zyzz_ _yzzz_
#define _zzyz_ _yzzz_
#define _zzzy_ _yzzz_
/* zzzz */
#define _zzzz_ 15
#endif
